import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score, davies_bouldin_score
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
from datetime import datetime


def load_sales_data(csv_path: Path) -> pd.DataFrame:
    """Read the cleaned sales CSV and filter for 2023-2025 data."""
    # Read the CSV file with semicolon separator
    df = pd.read_csv(csv_path, sep=';')
    # Convert Date column to datetime format for time-based calculations
    df['Date'] = pd.to_datetime(df['Date'], format='%d/%m/%y')
    # Filter only years 2023-2025 to match project scope
    df = df[df['Year'].between(2023, 2025)]
    return df


def aggregate_customer_features(df: pd.DataFrame) -> pd.DataFrame:
    """Aggregate transaction-level data to customer-level features."""
    # Group all transactions by Customer ID to get per-customer metrics
    customer_agg = df.groupby('Customer ID').agg({
        # Total revenue generated by this customer (Monetary in RFM)
        'Total Spent': 'sum',
        # Count of transactions (Frequency in RFM)
        'Transaction ID': 'count',
        # Sum of all gross profit from this customer
        'Gross_Profit_After_Discount': 'sum',
        # Average profit margin percentage across all transactions
        'Gross_Margin_%': 'mean',
        # Customer demographic - take first occurrence (same for all rows)
        'Customer Age': 'first',
        # How long customer has been with company (years)
        'Tenure (Years)': 'first',
        # Loyalty tier (Standard, Gold, Platinum)
        'Membership Level': 'first',
        # Geographic region for targeting
        'Region': 'first',
        # Most recent purchase date for recency calculation
        'Date': 'max',
    }).reset_index()

    # Rename columns for clarity
    customer_agg.rename(columns={
        'Transaction ID': 'Transaction_Frequency',
        'Total Spent': 'Total_Spent',
        'Gross_Profit_After_Discount': 'Total_Gross_Profit',
        'Gross_Margin_%': 'Avg_Gross_Margin',
        'Date': 'Last_Purchase_Date',
    }, inplace=True)

    return customer_agg


def engineer_features(customer_df: pd.DataFrame, reference_date: datetime) -> pd.DataFrame:
    """Create derived features for better clustering."""
    # Calculate Average Order Value (AOV) = Total Spent / Number of Transactions
    customer_df['AOV'] = customer_df['Total_Spent'] / customer_df['Transaction_Frequency']

    # Calculate Recency (days since last purchase) - lower is better
    customer_df['Recency'] = (reference_date - customer_df['Last_Purchase_Date']).dt.days

    # Encode Membership Level as ordinal: Standard(0) < Gold(1) < Platinum(2)
    membership_map = {'Standard': 0, 'Gold': 1, 'Platinum': 2}
    customer_df['Membership_Encoded'] = customer_df['Membership Level'].map(membership_map)

    # One-hot encode Region for geographic segmentation
    region_dummies = pd.get_dummies(customer_df['Region'], prefix='Region')
    customer_df = pd.concat([customer_df, region_dummies], axis=1)

    return customer_df


def handle_outliers(customer_df: pd.DataFrame, columns: list, lower_pct=1, upper_pct=99) -> pd.DataFrame:
    """Apply winsorization to cap extreme outliers while preserving high-value customers."""
    df_copy = customer_df.copy()

    for col in columns:
        # Calculate percentile thresholds
        lower_bound = df_copy[col].quantile(lower_pct / 100)
        upper_bound = df_copy[col].quantile(upper_pct / 100)

        # Cap values at the thresholds (winsorization)
        df_copy[col] = df_copy[col].clip(lower=lower_bound, upper=upper_bound)

    return df_copy


def prepare_features_for_clustering(customer_df: pd.DataFrame) -> tuple:
    """Select and scale features for K-Means clustering."""
    # Define feature columns for clustering (numerical + encoded)
    feature_cols = [
        'Total_Spent',              # Monetary value (RFM)
        'Transaction_Frequency',    # Frequency (RFM)
        'Recency',                  # Recency (RFM)
        'AOV',                      # Average order value
        'Total_Gross_Profit',       # Profitability
        'Avg_Gross_Margin',         # Margin efficiency
        'Tenure (Years)',           # Customer loyalty/age
        'Customer Age',             # Demographics
        'Membership_Encoded',       # Loyalty tier
    ]

    # Add all Region dummy columns (one-hot encoded)
    region_cols = [col for col in customer_df.columns if col.startswith('Region_')]
    feature_cols.extend(region_cols)

    # Extract feature matrix
    X = customer_df[feature_cols].copy()

    # Fill any missing values with median (robust to outliers)
    X = X.fillna(X.median())

    # Standardize features (mean=0, std=1) - critical for K-Means distance calculations
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)

    return X_scaled, feature_cols, scaler


def find_optimal_k(X_scaled, k_range=range(2, 11)) -> tuple:
    """Use Elbow Method and Silhouette Score to determine optimal number of clusters."""
    # Initialize lists to store evaluation metrics
    inertias = []           # Within-cluster sum of squares (lower is better)
    silhouette_scores = []  # Cluster separation metric (higher is better)
    davies_bouldin_scores = []  # Cluster separation index (lower is better)

    # Test different values of k (number of clusters)
    for k in k_range:
        # Initialize K-Means with k-means++ for smart centroid initialization
        kmeans = KMeans(
            n_clusters=k,
            init='k-means++',    # Smart initialization to avoid poor local minima
            n_init=10,           # Run algorithm 10 times with different seeds
            max_iter=300,        # Maximum iterations per run
            random_state=42,     # For reproducibility
        )

        # Fit model and get cluster labels
        labels = kmeans.fit_predict(X_scaled)

        # Calculate and store metrics
        inertias.append(kmeans.inertia_)
        silhouette_scores.append(silhouette_score(X_scaled, labels))
        davies_bouldin_scores.append(davies_bouldin_score(X_scaled, labels))

    # Find k with highest silhouette score (primary metric)
    optimal_k = list(k_range)[np.argmax(silhouette_scores)]

    return optimal_k, inertias, silhouette_scores, davies_bouldin_scores, k_range


def fit_kmeans_model(X_scaled, n_clusters: int) -> tuple:
    """Fit final K-Means model with optimal number of clusters."""
    # Initialize final model with best k
    kmeans = KMeans(
        n_clusters=n_clusters,
        init='k-means++',
        n_init=10,
        max_iter=300,
        random_state=42,
    )

    # Fit model and get cluster assignments
    cluster_labels = kmeans.fit_predict(X_scaled)

    # Calculate final evaluation metrics
    silhouette = silhouette_score(X_scaled, cluster_labels)
    davies_bouldin = davies_bouldin_score(X_scaled, cluster_labels)

    return kmeans, cluster_labels, silhouette, davies_bouldin


def create_cluster_profiles(customer_df: pd.DataFrame, cluster_labels) -> pd.DataFrame:
    """Generate statistical profiles for each cluster."""
    # Add cluster assignments to customer dataframe
    customer_df['Cluster'] = cluster_labels

    # Aggregate key metrics by cluster
    profiles = customer_df.groupby('Cluster').agg({
        'Customer ID': 'count',                      # Cluster size
        'Total_Spent': ['mean', 'median', 'std'],    # Spending patterns
        'Transaction_Frequency': ['mean', 'median'], # Purchase frequency
        'Recency': ['mean', 'median'],               # Days since last purchase
        'AOV': ['mean', 'median'],                   # Average order value
        'Total_Gross_Profit': ['mean', 'median'],    # Profitability
        'Avg_Gross_Margin': 'mean',                  # Margin efficiency
        'Tenure (Years)': 'mean',                    # Customer age
        'Customer Age': 'mean',                      # Demographics
        'Membership Level': lambda x: x.mode()[0],   # Most common tier
    }).round(2)

    # Flatten multi-level column names
    profiles.columns = ['_'.join(col).strip('_') for col in profiles.columns.values]

    # Rename for clarity
    profiles.rename(columns={'Customer ID_count': 'Cluster_Size'}, inplace=True)

    return profiles


def visualize_elbow_silhouette(k_range, inertias, silhouette_scores, davies_bouldin_scores, optimal_k, out_dir: Path):
    """Create Elbow and Silhouette score plots for k selection."""
    # Create figure with 3 subplots
    fig, axes = plt.subplots(1, 3, figsize=(18, 5))

    # Plot 1: Elbow curve (inertia)
    axes[0].plot(list(k_range), inertias, marker='o', linewidth=2)
    axes[0].axvline(x=optimal_k, color='r', linestyle='--', label=f'Optimal k={optimal_k}')
    axes[0].set_xlabel('Number of Clusters (k)')
    axes[0].set_ylabel('Inertia (Within-Cluster Sum of Squares)')
    axes[0].set_title('Elbow Method')
    axes[0].legend()
    axes[0].grid(True, alpha=0.3)

    # Plot 2: Silhouette scores
    axes[1].plot(list(k_range), silhouette_scores, marker='o', color='green', linewidth=2)
    axes[1].axvline(x=optimal_k, color='r', linestyle='--', label=f'Optimal k={optimal_k}')
    axes[1].set_xlabel('Number of Clusters (k)')
    axes[1].set_ylabel('Silhouette Score')
    axes[1].set_title('Silhouette Score Analysis')
    axes[1].legend()
    axes[1].grid(True, alpha=0.3)

    # Plot 3: Davies-Bouldin Index
    axes[2].plot(list(k_range), davies_bouldin_scores, marker='o', color='orange', linewidth=2)
    axes[2].axvline(x=optimal_k, color='r', linestyle='--', label=f'Optimal k={optimal_k}')
    axes[2].set_xlabel('Number of Clusters (k)')
    axes[2].set_ylabel('Davies-Bouldin Index')
    axes[2].set_title('Davies-Bouldin Index (Lower is Better)')
    axes[2].legend()
    axes[2].grid(True, alpha=0.3)

    # Save figure
    plt.tight_layout()
    plt.savefig(out_dir / 'elbow_silhouette_analysis.png', dpi=200, bbox_inches='tight')
    plt.close()


def visualize_clusters_pca(X_scaled, cluster_labels, optimal_k, out_dir: Path):
    """Reduce to 2D using PCA and visualize cluster assignments."""
    # Apply PCA to reduce to 2 dimensions for visualization
    pca = PCA(n_components=2, random_state=42)
    X_pca = pca.fit_transform(X_scaled)

    # Create scatter plot
    plt.figure(figsize=(12, 8))
    scatter = plt.scatter(
        X_pca[:, 0],
        X_pca[:, 1],
        c=cluster_labels,
        cmap='viridis',
        alpha=0.6,
        s=50,
        edgecolors='k',
        linewidths=0.5,
    )

    # Add cluster centroids (transform to PCA space)
    # Note: This is approximate since centroids are in original scaled space
    plt.xlabel(f'Principal Component 1 ({pca.explained_variance_ratio_[0]:.2%} variance)')
    plt.ylabel(f'Principal Component 2 ({pca.explained_variance_ratio_[1]:.2%} variance)')
    plt.title(f'Customer Clusters Visualization (k={optimal_k})')
    plt.colorbar(scatter, label='Cluster')
    plt.grid(True, alpha=0.3)

    # Save figure
    plt.tight_layout()
    plt.savefig(out_dir / 'clusters_pca_visualization.png', dpi=200, bbox_inches='tight')
    plt.close()


def visualize_cluster_profiles(profiles: pd.DataFrame, out_dir: Path):
    """Create radar chart comparing cluster profiles."""
    # Select key metrics for radar chart
    metrics = [
        'Total_Spent_mean',
        'Transaction_Frequency_mean',
        'AOV_mean',
        'Total_Gross_Profit_mean',
        'Tenure (Years)_mean',
    ]

    # Normalize metrics to 0-1 scale for comparison
    profile_data = profiles[metrics].copy()
    for col in metrics:
        min_val = profile_data[col].min()
        max_val = profile_data[col].max()
        # Avoid division by zero
        if max_val - min_val > 0:
            profile_data[col] = (profile_data[col] - min_val) / (max_val - min_val)

    # Number of variables
    num_vars = len(metrics)
    angles = np.linspace(0, 2 * np.pi, num_vars, endpoint=False).tolist()
    angles += angles[:1]  # Complete the circle

    # Create radar chart
    fig, ax = plt.subplots(figsize=(10, 10), subplot_kw=dict(projection='polar'))

    # Plot each cluster
    for cluster_id in profile_data.index:
        values = profile_data.loc[cluster_id].tolist()
        values += values[:1]  # Complete the circle
        ax.plot(angles, values, 'o-', linewidth=2, label=f'Cluster {cluster_id}')
        ax.fill(angles, values, alpha=0.15)

    # Customize chart
    ax.set_theta_offset(np.pi / 2)
    ax.set_theta_direction(-1)
    ax.set_xticks(angles[:-1])
    # Simplify labels for readability
    labels = [m.replace('_mean', '').replace('_', ' ') for m in metrics]
    ax.set_xticklabels(labels, size=10)
    ax.set_ylim(0, 1)
    ax.set_title('Cluster Profiles Comparison (Normalized)', size=14, pad=20)
    ax.legend(loc='upper right', bbox_to_anchor=(1.3, 1.1))
    ax.grid(True)

    # Save figure
    plt.tight_layout()
    plt.savefig(out_dir / 'cluster_profiles_radar.png', dpi=200, bbox_inches='tight')
    plt.close()


def visualize_cluster_distributions(customer_df: pd.DataFrame, out_dir: Path):
    """Create box plots showing distribution of key metrics by cluster."""
    # Select key metrics to visualize
    metrics = ['Total_Spent', 'Transaction_Frequency', 'Recency', 'AOV']

    # Create 2x2 subplot grid
    fig, axes = plt.subplots(2, 2, figsize=(14, 10))
    axes = axes.flatten()

    # Create box plot for each metric
    for idx, metric in enumerate(metrics):
        customer_df.boxplot(
            column=metric,
            by='Cluster',
            ax=axes[idx],
            patch_artist=True,
        )
        axes[idx].set_title(f'{metric} by Cluster')
        axes[idx].set_xlabel('Cluster')
        axes[idx].set_ylabel(metric)
        # Remove automatic title from pandas
        axes[idx].get_figure().suptitle('')

    # Overall title
    fig.suptitle('Distribution of Key Metrics by Cluster', fontsize=16, y=1.00)

    # Save figure
    plt.tight_layout()
    plt.savefig(out_dir / 'cluster_distributions.png', dpi=200, bbox_inches='tight')
    plt.close()


def save_artifacts(customer_df: pd.DataFrame, profiles: pd.DataFrame, optimal_k: int,
                   silhouette: float, davies_bouldin: float, out_dir: Path):
    """Save cluster assignments, profiles, and summary statistics."""
    # Create output directory if it doesn't exist
    out_dir.mkdir(parents=True, exist_ok=True)

    # Save customer cluster assignments
    output_cols = [
        'Customer ID', 'Cluster', 'Total_Spent', 'Transaction_Frequency',
        'Recency', 'AOV', 'Tenure (Years)', 'Customer Age', 'Membership Level', 'Region'
    ]
    customer_output = customer_df[output_cols].copy()

    # Try to save CSV, handle permission errors
    csv_path = out_dir / 'customer_clusters.csv'
    try:
        customer_output.to_csv(csv_path, index=False)
        print(f"✓ Saved cluster assignments to {csv_path}")
    except PermissionError:
        # If file is open, save to alternative path
        alt_path = out_dir / 'customer_clusters_out.csv'
        print(f"⚠ Could not write {csv_path} (file may be open). Saved to {alt_path}.")
        customer_output.to_csv(alt_path, index=False)

    # Save cluster profiles
    profile_path = out_dir / 'cluster_profiles.csv'
    try:
        profiles.to_csv(profile_path)
        print(f"✓ Saved cluster profiles to {profile_path}")
    except PermissionError:
        alt_path = out_dir / 'cluster_profiles_out.csv'
        print(f"⚠ Could not write {profile_path} (file may be open). Saved to {alt_path}.")
        profiles.to_csv(alt_path)

    # Save summary statistics to text file
    summary_path = out_dir / 'clustering_summary.txt'
    with open(summary_path, 'w') as f:
        f.write("=" * 60 + "\n")
        f.write("K-MEANS CLUSTERING SUMMARY\n")
        f.write("=" * 60 + "\n\n")
        f.write(f"Optimal Number of Clusters: {optimal_k}\n")
        f.write(f"Silhouette Score: {silhouette:.4f}\n")
        f.write(f"Davies-Bouldin Index: {davies_bouldin:.4f}\n\n")
        f.write("=" * 60 + "\n")
        f.write("CLUSTER PROFILES\n")
        f.write("=" * 60 + "\n\n")
        f.write(profiles.to_string())

    print(f"✓ Saved summary to {summary_path}")


def main():
    """Run the complete clustering pipeline end-to-end."""
    # Define paths relative to script location
    base_dir = Path(__file__).resolve().parent.parent.parent
    csv_path = base_dir / 'datasets' / 'Sales_Cleaned.csv'
    out_dir = base_dir / 'Clustering' / 'python'

    print("=" * 60)
    print("CUSTOMER SEGMENTATION CLUSTERING PIPELINE")
    print("=" * 60)

    # Step 1: Load data
    print("\n[1/9] Loading sales data...")
    df = load_sales_data(csv_path)
    print(f"✓ Loaded {len(df):,} transactions")

    # Step 2: Aggregate to customer level
    print("\n[2/9] Aggregating to customer-level features...")
    customer_df = aggregate_customer_features(df)
    print(f"✓ Aggregated {len(customer_df):,} unique customers")

    # Step 3: Engineer features
    print("\n[3/9] Engineering features (RFM, AOV, encoding)...")
    # Use most recent date in dataset as reference
    reference_date = df['Date'].max()
    customer_df = engineer_features(customer_df, reference_date)
    print(f"✓ Created derived features (Reference date: {reference_date.date()})")

    # Step 4: Handle outliers
    print("\n[4/9] Handling outliers (winsorization)...")
    outlier_cols = ['Total_Spent', 'Transaction_Frequency', 'Total_Gross_Profit']
    customer_df = handle_outliers(customer_df, outlier_cols)
    print(f"✓ Applied winsorization to {len(outlier_cols)} columns")

    # Step 5: Prepare and scale features
    print("\n[5/9] Scaling features for K-Means...")
    X_scaled, feature_cols, scaler = prepare_features_for_clustering(customer_df)
    print(f"✓ Standardized {len(feature_cols)} features")

    # Step 6: Find optimal k
    print("\n[6/9] Finding optimal number of clusters (k=2 to 10)...")
    optimal_k, inertias, silhouette_scores, davies_bouldin_scores, k_range = find_optimal_k(X_scaled)
    print(f"✓ Optimal k determined: {optimal_k}")
    print(f"  - Silhouette Score: {silhouette_scores[optimal_k - 2]:.4f}")

    # Step 7: Fit final model
    print(f"\n[7/9] Fitting K-Means model with k={optimal_k}...")
    kmeans, cluster_labels, silhouette, davies_bouldin = fit_kmeans_model(X_scaled, optimal_k)
    print(f"✓ Model fitted successfully")
    print(f"  - Final Silhouette Score: {silhouette:.4f}")
    print(f"  - Final Davies-Bouldin Index: {davies_bouldin:.4f}")

    # Step 8: Create cluster profiles
    print("\n[8/9] Generating cluster profiles...")
    profiles = create_cluster_profiles(customer_df, cluster_labels)
    print(f"✓ Created profiles for {optimal_k} clusters")
    print("\nCluster Sizes:")
    for cluster_id in range(optimal_k):
        size = profiles.loc[cluster_id, 'Cluster_Size']
        pct = (size / len(customer_df)) * 100
        print(f"  - Cluster {cluster_id}: {int(size):,} customers ({pct:.1f}%)")

    # Step 9: Save outputs and visualizations
    print("\n[9/9] Saving artifacts and visualizations...")
    save_artifacts(customer_df, profiles, optimal_k, silhouette, davies_bouldin, out_dir)

    # Generate visualizations
    visualize_elbow_silhouette(k_range, inertias, silhouette_scores, davies_bouldin_scores, optimal_k, out_dir)
    print(f"✓ Saved elbow/silhouette analysis")

    visualize_clusters_pca(X_scaled, cluster_labels, optimal_k, out_dir)
    print(f"✓ Saved PCA cluster visualization")

    visualize_cluster_profiles(profiles, out_dir)
    print(f"✓ Saved cluster profiles radar chart")

    visualize_cluster_distributions(customer_df, out_dir)
    print(f"✓ Saved cluster distribution box plots")

    print("\n" + "=" * 60)
    print("CLUSTERING COMPLETE!")
    print("=" * 60)
    print(f"\nOutputs saved to: {out_dir}")
    print("\nGenerated files:")
    print("  - customer_clusters.csv: Cluster assignments for each customer")
    print("  - cluster_profiles.csv: Statistical summary of each cluster")
    print("  - clustering_summary.txt: Overall metrics and profiles")
    print("  - elbow_silhouette_analysis.png: K selection analysis")
    print("  - clusters_pca_visualization.png: 2D cluster visualization")
    print("  - cluster_profiles_radar.png: Radar chart comparison")
    print("  - cluster_distributions.png: Box plots by cluster")


if __name__ == '__main__':
    main()
